<!-- #region -->
## Individual assignment 1
rubric={correctness:1}

The purpose of this assignment is to ensure that everyone does some self-learning and obtains practice on using docopt to create command line arguements in scripts, as well as creating releases on GitHub. This assignment will be graded for completion. You must attempt all questions to get the grade.

### Submission instructions

- You should commit and push your changes to the public GitHub.com repository you created in exercise 1. 
- You should submit a `.html` version of this assignment to Canvas.

### Exercise 1

Create a public repository on GitHub.com called `docopt_demo`. Paste the url below:

> Your answer here: https://github.com/RussDim/docopt_demo

### Exercise 2

**Getting documentation from a {docopt} R script**

In [this repo](https://github.ubc.ca/MDS-2022-23/DSCI_522_dsci-workflows_students), in the `src` directory, you will find a script named `demo.R`. Access the documentation for that script from the command line by running the script with the `--help` option (and no other options or arguments). Paste the documentation that was printed out to your terminal below.

> ```
> Your answer here:
Rscript demo.R --help
Warning message:
package 'docopt' was built under R version 4.2.2 
This script prints out docopt args.
Usage: demo.R <arg1> --arg2=<arg2> [--arg3=<arg3>]
Options:
<arg>             Takes any value (this is a required positional argument)
--arg2=<arg2>     Takes any value (this is a required option)
[--arg3=<arg3>]   Takes any value (this is an optional option)
> ```

### Exercise 3

**What does `docopt` return in R?**

Run the `demo.R` script giving it appropriate arguments to see what the `docopt` function in R returns. Try setting and not setting a value for `arg3`. Describe what you observed below.

For options, you need to include the `--` in the command line call, for example:
```
Rscript src/my_script something --anoption=something more
```

> Your answer here
```
$ Rscript demo.R first --arg2=second --arg3=third
Warning message:
package 'docopt' was built under R version 4.2.2
List of 6
 $ --arg2: chr "second"
 $ --arg3: chr "third"
 $ <arg1>: chr "first"
 $ arg2  : chr "second"
 $ arg3  : chr "third"
 $ arg1  : chr "first"
NULL
[1] "list"

Comment: The docopt function prints out the docopt arguments.  The first argument is required, so if not provided, the execution is halted.  The second argument is a required option, which if not provided will also halt execution.  The third argument is an optional option and the script will run regardless of whether it is provided or not.

```



### Exercise 4

**Break this script!**

Run the `demo.R` script and find at least 3 different ways to break it by changing the values or order of the command line arguments at the command line (do not modify the script). Document how you did this below.

> 1. Your answer here: By leaving out the first required option `<arg2>` and only providing the first argument the script halts execution
```
$ Rscript demo.R first 
Warning message:
package 'docopt' was built under R version 4.2.2 
Error: This script prints out docopt args.
Usage: demo.R <arg1> --arg2=<arg2> [--arg3=<arg3>]

Options:
<arg>             Takes any value (this is a required positional argument)
--arg2=<arg2>     Takes any value (this is a required option) 
[--arg3=<arg3>]   Takes any value (this is an optional option)
Execution halted
```

> 2. Your answer here: Writing `arg1` in front of the first argument, leads to an error in the execution, and consequently it is halted because the argument must be provided with its value only and no positional code.
```
$ Rscript demo.R arg1 = first --arg2=second 
Warning message:
package 'docopt' was built under R version 4.2.2 
Error: This script prints out docopt args.
Usage: demo.R <arg1> --arg2=<arg2> [--arg3=<arg3>]

Options:
<arg>             Takes any value (this is a required positional argument)
--arg2=<arg2>     Takes any value (this is a required option)
[--arg3=<arg3>]   Takes any value (this is an optional option)
Execution halted
```
> 3. Your answer here: By leaving out the option specification in front of the third argument i.e. not specifying `--arg3=`, which is an optional option, the script returns an error and halts execution.

```
$ Rscript demo.R first --arg2=second third
Warning message:
package 'docopt' was built under R version 4.2.2 
Error: This script prints out docopt args.
Usage: demo.R <arg1> --arg2=<arg2> [--arg3=<arg3>]

Options:
<arg>             Takes any value (this is a required positional argument)
--arg2=<arg2>     Takes any value (this is a required option)
[--arg3=<arg3>]   Takes any value (this is an optional option)
Execution halted
```


### Exercise 5

**Add a new optional positional argument**

Copy the `demo.R` script into your `docopt_demo` repo, and then edit it to add a new positional argument that is optional. Commit this change and push it to your `docopt_demo` repository.  Paste the URL to this commit below:

> Your answer here: https://github.com/RussDim/docopt_demo/commit/15435527e6a996b5cedb60e1f8d32bbfd7b57d57

Added a new line in options after the first argument putting `arg_opt` in square brackets:
```
Options:
<arg>             Takes any value (this is a required positional argument)
[<arg_opt>]       Takes any value (this is an optiotnal positional argument)
--arg2=<arg2>     Takes any value (this is a required option)
[--arg3=<arg3>]   Takes any value (this is an optional option)
" -> doc
```
Out put is as follows when arg_opt skipped:
```
$ Rscript demo.R first --arg2=second --arg3=third
Warning message:
package 'docopt' was built under R version 4.2.2 
List of 8
 $ --arg2   : chr "second"
 $ --arg3   : chr "third" 
 $ <arg1>   : chr "first" 
 $ <arg_opt>: NULL        
 $ arg2     : chr "second"
 $ arg3     : chr "third" 
 $ arg1     : chr "first" 
 $ arg_opt  : NULL        
NULL
[1] "list"

```
Out put is as follows when arg_opt is added:

```
$ Rscript demo.R first optional --arg2=second --arg3=third
Warning message:
package 'docopt' was built under R version 4.2.2 
List of 8
 $ --arg2   : chr "second"  
 $ --arg3   : chr "third"   
 $ <arg1>   : chr "first"   
 $ <arg_opt>: chr "optional"
 $ arg2     : chr "second"  
 $ arg3     : chr "third"   
 $ arg1     : chr "first"   
 $ arg_opt  : chr "optional"
NULL
[1] "list"

```


### Exercise 6

**Add a main function**

Modify the `demo.R` script further so that the print statements happen inside a main function. Commit this change and push it to your `docopt_demo` repository.  Paste the URL to this commit below:

> Your answer here:  https://github.com/RussDim/docopt_demo/commit/dcf2e08b0ffea45ec621ae61b6edee51d6e1457b
The body of demo.R was changed to look as follows:
```
library(docopt)
opt <- docopt(doc)
main <- function() {
print(opt)
print(typeof(opt))
    }

main()
```

output from terminal:
```
$ Rscript demo.R first optional --arg2=second --arg3=third
Warning message:
package 'docopt' was built under R version 4.2.2
List of 8
 $ --arg2   : chr "second"
 $ --arg3   : chr "third"
 $ <arg1>   : chr "first"
 $ <arg_opt>: chr "optional"
 $ arg2     : chr "second"
 $ arg3     : chr "third"
 $ arg1     : chr "first"
 $ arg_opt  : chr "optional"
NULL
[1] "list"
```

### Exercise 7

**What does `docopt` return in Python?**

In [this repo](https://github.ubc.ca/MDS-2022-23/DSCI_522_dsci-workflows_students), in the `src` directory, you will find a script named `demo.py`. Run the `demo.py` script giving it appropriate arguments to see what the `docopt` function in Python returns. Try setting and not setting a value for `arg3`. How does this differ from what `docopt` returns in R? Describe what you observed below.

> Your answer here: The code collects the arguments and options in a dictionary instead of a list, which was the case in R.  Furthermore R generates a list of six items - once the input from terminal and once the actual values, while Pythton's dictionary only contains the values with keys as defined in the comments of the document.

Running with all arguments and options:
```
$ python demo.py first --arg2=second --arg3=third
{'--arg2': 'second',
 '--arg3': 'third',
 '<arg1>': 'first'}
<class 'docopt.Dict'>
```
Running without `arg3`:
```
$ python demo.py first --arg2=second
{'--arg2': 'second',
 '--arg3': None,    
 '<arg1>': 'first'} 
<class 'docopt.Dict'>
```


### Exercise 8

**Add a new optional positional argument**

Copy the `demo.py` script into your `docopt_demo` repo, and then edit it to add a new positional argument that is optional. Commit this change and push it to your `docopt_demo` repository.  Paste the URL to this commit below:

> Your answer here: https://github.com/RussDim/docopt_demo/commit/08ca2ecfb708ded6c7a54b0a317aa5bbdb2adede

Output from demo.py when using positional argument:
```
$ python demo.py first --arg_opt=optional --arg2=second --arg3=three
{'--arg2': 'second',
 '--arg3': 'three',
 '--arg_opt': 'optional',
 '<arg1>': 'first'}
<class 'docopt.Dict'>
```

### Exercise 9

Modify the `demo.py` script further so that the print statements happen inside a main function. Commit this change and push it to your `docopt_demo` repository.  Paste the URL to this commit below:

> Your answer here: https://github.com/RussDim/docopt_demo/commit/48a429e419909f02540db3e6e78f231c95de8bd5

Output from running demo.py with `main` function:
```
$ python demo.py first --arg_opt=optional --arg2=second --arg3=three
{'--arg2': 'second',
 '--arg3': 'three',
 '--arg_opt': 'optional',
 '<arg1>': 'first'}
<class 'docopt.Dict'>
```

### Exercise 10

Create a release in your `docopt_demo` repo called `0.1.0`. Paste the URL to this release below. 

*Hint: See the [creating a release docs](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository#creating-a-release) to help complete this exercise.

> Your answer here: https://github.com/RussDim/docopt_demo/releases/tag/0.1.0
<!-- #endregion -->

```{python}

```
